version: '2'
services:
  cam-web:
    build: .
    ports:
      - "80:8000"
    links:
      - cam-redis
    container_name: cam-running
  cam-redis:
    image: "redis:3.0"
    expose:
      - "6379"
    container_name: cam-redis